### ISSUE TITLE
DidHide event

### ISSUE THREAD

**Issue by skuske** [ilyainyushin/ISMessages#10]
A 'DidHide' event would also me very helpful if one wnats to display multiple messages one after the other... Thanks! :)

**Comment by ilyainyushin** [comment]
@skuske Hello! Okay. Coming soon. Thx. :)

**Comment by ilyainyushin** [comment]
Hey @skuske , thank you for waiting. I did that. 

**v. 1.2**

``` ruby
  pod update ISMessages
```
