### ISSUE TITLE
Icon nil

### ISSUE THREAD

**Issue by Bejil** [ilyainyushin/ISMessages#11]
Hi,

you should consider testing `iconImage` in the `initCardAlertWithTitle` function.
`self.iconImageSize = iconImage==nil?CGSizeZero:CGSizeMake(35.f, 35.f);`

Like this the notification can have no image and full width texts.

**Comment by ilyainyushin** [comment]
Hey @Bejil , thank you for waiting. I did that. 

**v. 1.2**

``` ruby
  pod update ISMessages
```
