### ISSUE TITLE
iPhone X appearance problem

### ISSUE THREAD

**Issue by skuske** [ilyainyushin/ISMessages#16]
If displayed at the top or at the bottom, messages do show up in the safe areas on iPhone X. Any way to fix that, i.e. make it aware of the safe area layout? Thanks.

**Comment by hilalbaig** [comment]
I have fixed iPhone X appearance issue in #17 

In method `- (void)showInMain()` add these lines;
`if ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPhone && UIScreen.mainScreen.nativeBounds.size.height == 2436)  {
            alertYPosition += (_alertPosition == ISAlertPositionBottom) ? -30.f : 30.f;;
        }`

**Comment by skuske** [comment]
That is not a complete solution as it does not reflect landscape mode and left<>right safe zones.
