### ISSUE TITLE
Invalid CFBundleSupportedPlatforms

### ISSUE THREAD

**Issue by spnkr** [ilyainyushin/ISMessages#18]
I had trouble publishing an app using this (via the cocoapod) to the app store. Got an 'invalid CFBundleSupportedPlatforms' error—it was using iPhoneSimulator not iPhoneOS somehow. I fixed it by manually editing a .plist that xcode generated after the build, but there's probably a better way?

**Comment by ikorich** [comment]
I use it in few project, there are no publishing problems
