### ISSUE TITLE
hotspot status bar support

### ISSUE THREAD

**Issue by Yelles** [ilyainyushin/ISMessages#7]
Hi,

Layout is ruined when hotspot status bar appears.

Regards

![img_3237](https://cloud.githubusercontent.com/assets/689478/18798454/e9ea66ba-81d2-11e6-8a29-8b3be7f6cd43.PNG)
![img_3238](https://cloud.githubusercontent.com/assets/689478/18798455/ea0c4e6a-81d2-11e6-856c-761b91cfdf9a.PNG)

**Comment by ilyainyushin** [comment]
Hello @Yelles. Fixed it.

v. 1.0.3
`pod update` :)

**Comment by Yelles** [comment]
great, thanks
