### ISSUE TITLE
How do I customize the colors 

### ISSUE THREAD

**Issue by hiroshihorie** [ilyainyushin/ISMessages#8]

**Comment by ilyainyushin** [comment]
@HiroshiHorie text color or background?

**Comment by hiroshihorie** [comment]
I like the presentation logic and animation but I want to at least customize : 
- background & foreground colors & fonts
- text alignment
- corner radius
- tap action

And don't show "Empty title!" for title = nil, because the point is to make the title empty.

**Comment by ilyainyushin** [comment]
@HiroshiHorie Wait 12 hrs pls and this will be done 😊

**Comment by ilyainyushin** [comment]
Hey @HiroshiHorie, thank you for waiting. I did that. 

**v. 1.1**

``` ruby
  pod update ISMessages
```
